#!/bin/bash

# Use neovim for vim if present
[ -x "$(command -v nvim)" ] && vimdiff="nvim -d"

# Vervosity and settings that you pretty much just always are going to wand
alias \
    bc="bc -ql" \
    cp="cp -vi" \
    df="df -h" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    nsxiv="nsxiv -a" \
    rm="rm -vI" \
    wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts" \
    keychain="keychain --dir $XDG_RUNTIME_DIR/keychain"

# Colorize commands when possible
alias \
    diff="diff --color=auto" \
    grep="rg --color=auto" \
    ip="ip -color=auto" \
    less="moar" \
    ls="eza -a --icons --group-directories-first"

# These common commands ate just too long! Abbreviate them
alias \
    battery="acpi" \
    code="vscodium" \
    day="redshift -PO 6500" \
    dv="doasedit" \
    e="$EDITOR" \
    fetch="fastfetch" \
    g="git" \
    gP="git push" \
    ga="git add" \
    gc="git commit" \
    gd="git diff" \
    gp="git pull" \
    gs="git status" \
    j="joshutoub" \
    lf="lfub" \
    lg="lazygit" \
    lzd="lazydocker" \
    lock="swaylock" \
    night="redshift -PO 4500" \
    py="python" \
    sv="rsv" \
    typst-port="ss -tunlp | rg tinymist" \
    v="$EDITOR" \
    weather="curl wttr.in/" \
    wg-down="wg-quick down wg0" \
    wg-up="wg-quick up wg0" \
    ww="$EDITOR ~/neorg/" \
    yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config" \
    yy="yazi"

# doas not required for some system commands
for command in mount umount rsv sv pacman updatedb su shutdown poweroff reboot zzz systemctl wg wg-quick; do
    alias "$command=doas $command"
done
unset command
