#!/bin/sh

autostart="picom nextcloud telegram-desktop spotify-launcher discord transmission-daemon librewolf discord syncthing mullvad-vpn"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done
# >/dev/null 2>&1

setxkbmap lv &
remaps & # run the remaps script, switching caps/esc and more; check it for more info
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 75 --output HDMI-A-0 --mode 1920x1080 --rate 60 --left-of DisplayPort-0 &
# spotifyd --no-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
