#:schema https://jj-vcs.github.io/jj/latest/config-schema.json
[user]
email = "dev@kristofers.xyz"
name = "Kristofers Solo"

[ui]
editor = "nvim"
default-command = "log"

[signing]
behavior = "own"
backend = "gpg"
# key = "$(cat ~/.config/jj/key)"
