# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 1000

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
vimcmd_symbol = "[❯](bold blue)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[line_break]
disabled = true

[cmd_duration]
min_time = 500
show_milliseconds = false
format = "took [$duration](bold yellow)"
