[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "arm"

[default_config.opts]
# compiler = "zig"
# compile_flags_txt = [
#   "cc",
#   "-x",
#   "assembler-with-cpp",
#   "-g",
#   "-Wall",
#   "-Wextra",
#   "-pedantic",
#   "-pedantic-errors",
#   "-std=c2y",
#   "-target",
#   "aarch64-linux-musl",
# ]
diagnostics = true
default_diagnostics = false
