packages = [ "wayland" ]

[variables]
dpi = "96"
font_size = "10"
terminal = "alacritty"
browser = "floorp"
waybar_font_size = "12px"

[files]
"config/niri/config-desktop.kdl" = "~/.config/niri/config.kdl"
