node.rules = [
  {
    matches = [
      {
        node.name  = "audio-src"
        media.role = "Music"
      }
    ]
    apply_properties = {
      node.nick        = "Spotify"
      application.name = "Spotify"
    }
  }
]
